name: 1-Website Monitor

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  check_websites:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      # Download previous website hash file if it exists
      - name: Download previous website hash file
        id: download_artifact
        uses: actions/download-artifact@v4
        with:
          name: website-hashes
          path: .
        continue-on-error: true  # Verhindert einen Abbruch, wenn kein Artifact vorhanden ist

      # Check if website_hashes.txt exists after download
      - name: Check if website_hashes.txt exists
        id: check_file
        run: |
          if [ -f website_hashes.txt ]; then
            echo "File exists."
            echo "exists=true" >> $GITHUB_ENV
          else
            echo "File does not exist."
            echo "Creating an empty website_hashes.txt."
            echo "exists=false" >> $GITHUB_ENV
            touch website_hashes.txt  # Erstelle eine leere Datei, falls sie nicht existiert
          fi

      # Run the script to check websites
      - name: Run website check script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: |
          python 1_check_updates.py

      - name: Commit und Push Änderungen
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git add website_hashes.txt
          git commit -m "Update website_hashes.txt" || echo "Keine Änderungen"
          git push

      # Upload website_hashes.txt as an artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: website-hashes
          path: website_hashes.txt
