name: 1-Website Monitor

on:
  workflow_dispatch:

jobs:
  check_websites:
    runs-on: ubuntu-latest
    
    steps:
    - name: Repository klonen
      uses: actions/checkout@v4

    - name: Setze Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Installiere Abhängigkeiten
      run: |
        python -m pip install --upgrade pip
        pip install requests

        # Debugging
    - name: Debugging Download Step
      run: |
        echo "Checking for the downloaded files:"
        ls -la

    # Debugging for checking existence
    - name: Debugging File Check
      run: |
        echo "Checking if website_hashes.txt exists:"
        if [ -f website_hashes.txt ]; then
          echo "File exists."
        else
          echo "File does not exist."
        fi

    # Download the previous artifact if it exists
    - name: Download previous website hash file
      id: download_artifact
      uses: actions/download-artifact@v3
      with:
        name: website-hashes
        path: .



    # Check if the file was downloaded
    - name: Check if website_hashes.txt exists
      id: check_file
      run: |
        if [ -f website_hashes.txt ]; then
          echo "File exists."
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "File does not exist."
          echo "exists=false" >> $GITHUB_ENV
        fi

    - name: Führe das Skript aus
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python 1_check_updates.py

    # Save the updated hashes as an artifact
    - name: Save website hash file as artifact
      if: env.exists == 'false'
      uses: actions/upload-artifact@v3
      with:
        name: website-hashes
        path: website_hashes.txt
