name: 1-Website Monitor

on:
  workflow_dispatch:

jobs:
  check_websites:
    runs-on: ubuntu-latest
    
    steps:
    - name: Repository klonen
      uses: actions/checkout@v4

    - name: Setze Up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Installiere Abhängigkeiten
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Save website hash file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: website-hashes
        path: website_hashes.txt

    - name: Führe das Skript aus
      env:
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
        RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
      run: python 1_check_updates.py

    - name: Download previous website hash file
      uses: actions/download-artifact@v3
      with:
        name: website-hashes
        path: .
