name: Check Website Updates

on:
  schedule:
    - cron: '5 * * * *'  # Führe jede Stunde aus

jobs:
  check_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Verwende die gewünschte Python-Version

      - name: Install requests
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run script
        run: python check_updates.py
