name: Check Websites for Changes

on:
  workflow_dispatch:

jobs:
  check_for_updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Restore hashes
        uses: actions/download-artifact@v2
        with:
          name: website_hashes

      - name: Check websites for changes
        run: python check_websites.py

      - name: Save hashes
        uses: actions/upload-artifact@v2
        with:
          name: website_hashes
          path: website_hashes.txt

      
      - name: Check websites for changes
        run: |
          python check_websites.py
        env:
          EMAIL_RECE: ${{ secrets.EMAIL_RECE }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
